AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates an a lambda function and an IAM execution role with a policy allowing access to everything. 

Resources:
    LambdaExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Principal:
                        Service:
                          - lambda.amazonaws.com
                    Action:
                      - sts:AssumeRole
            Description: Role for lambda execution
            Path: "/"
            Policies:
              - PolicyName: SudoAWSLambdaExecRole
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                      - Effect: Allow
                        Action: '*'
                        Resource: '*'

    TestLambda:
        Type: AWS::Lambda::Function
        Properties:
            Handler: index.handler
            Role:
                Fn::GetAtt:
                  - LambdaExecutionRole
                  - Arn
            Code: .\cam2text.py
            Runtime: python3.8
